/* Generated By:JavaCC: Do not edit this line. TimeConverterConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TimeConverterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int NUM = 3;
  /** RegularExpression Id. */
  int SECOND = 4;
  /** RegularExpression Id. */
  int MINUTE = 5;
  /** RegularExpression Id. */
  int HOUR = 6;
  /** RegularExpression Id. */
  int DAY = 7;
  /** RegularExpression Id. */
  int MONTH = 8;
  /** RegularExpression Id. */
  int YEAR = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<NUM>",
    "\"s\"",
    "\"m\"",
    "\"h\"",
    "\"d\"",
    "\"M\"",
    "\"y\"",
  };

}
